### ISSUE TITLE
Website cannot be reached

### ISSUE THREAD

**Issue by mandeep-s1ngh** [GreenTreeTeam/ChillingMusic#16]
Hi There, I stumbled across this repo for Hacktoberfest but it seems like your website is down. Some sort of DNS issue.

I have tried on 4g and wifi across different devices and browsers.

![image](https://github.com/GreenTreeTeam/ChillingMusic/assets/92678152/6c758b97-3077-45b0-8313-bee8a83d3e09)

**Comment by mandeep-s1ngh** [comment]
Closing this issue as it looks like this project is not being maintained anymore.

**Comment by adinetech** [comment]
Correct, we're not maintaining this project and the domain chillingmusic.cf no longer belongs to us.
