### ISSUE TITLE
[Bug] Invalid Version: undefined

### ISSUE THREAD

**Issue by Testing9067** [GreenTreeTeam/ChillingMusic#8]
Error when hosting it on 

https://vercel.com/

![7EC0A6E4-52EC-4550-9E6F-12660EBDB475](https://user-images.githubusercontent.com/70417277/119078663-7b0e1a00-b9ab-11eb-80c8-7803b4944755.jpeg)

**Comment by Testing9067** [comment]
I tried downgrading parcel to 1.12.3 didn’t work

**Comment by yashraj-n** [comment]
Do You have logo.png in /images/?

**Comment by Testing9067** [comment]
Yes I do have it

**Comment by Testing9067** [comment]
Found out a solution yet?

**Comment by yashraj-n** [comment]
I'll try hosting this site today on vercel

**Comment by Testing9067** [comment]
Ok thanks.

**Comment by AdineVikash** [comment]
Lol

**Comment by Testing9067** [comment]
Any fix yet? Please update me with the status

**Comment by SudhanPlayz** [comment]
> Any fix yet? Please update me with the status

No fixes yet, Its because of parcel's version. Our team will be working on this fix once our members get enough time!

**Comment by SudhanPlayz** [comment]
This bug won't come again when we merge [React Branch](https://github.com/GreenTreeTeam/ChillingMusic/tree/react) to [master](https://github.com/GreenTreeTeam/ChillingMusic/tree/master)

**Comment by Testing9067** [comment]
Ok
